SET FEEDBACK 1
SET NUMWIDTH 10
SET LINESIZE 80
SET TRIMSPOOL ON
SET TAB OFF
SET PAGESIZE 100

CONNECT op/&password_op@&connect_string

DROP TABLE Adresses     CASCADE CONSTRAINTS;
DROP TABLE Annonces   CASCADE CONSTRAINTS;
DROP TABLE BesoinClient   CASCADE CONSTRAINTS;
DROP TABLE Client   CASCADE CONSTRAINTS;  
DROP TABLE Echanges     CASCADE CONSTRAINTS;
DROP TABLE PersonnePhysique CASCADE CONSTRAINTS;
DROP TABLE Personnes   CASCADE CONSTRAINTS;
DROP TABLE Pressings        CASCADE CONSTRAINTS;
DROP TABLE Privileges CASCADE CONSTRAINTS;
DROP TABLE Roles   CASCADE CONSTRAINTS;
DROP TABLE attributs   CASCADE CONSTRAINTS;  
DROP TABLE lingeclient     CASCADE CONSTRAINTS;
DROP TABLE offres CASCADE CONSTRAINTS;
DROP TABLE promos   CASCADE CONSTRAINTS;
DROP TABLE services        CASCADE CONSTRAINTS;
DROP TABLE type_services CASCADE CONSTRAINTS;
DROP TABLE valeurattributs   CASCADE CONSTRAINTS;
DROP TABLE TypeLinges   CASCADE CONSTRAINTS; 
DROP TABLE Utilisateur   CASCADE CONSTRAINTS;


DROP SEQUENCE id_adresse_seq;
DROP SEQUENCE id_annonces_seq;
DROP SEQUENCE id_besoinClient_seq;
DROP SEQUENCE id_client_seq;
DROP SEQUENCE id_presonnePhysique_seq;
DROP SEQUENCE id_personne_seq;
DROP SEQUENCE id_pressings_seq;
DROP SEQUENCE id_privileges_seq;
DROP SEQUENCE attribut_id_seq;
DROP SEQUENCE lingeclient_id_seq;
DROP SEQUENCE service_id_seq;
DROP SEQUENCE valeurattribut_id_seq;
DROP SEQUENCE id_utilisateur_seq;

COMMIT;